"""Figure: does a gate sequence follow a clean path, or fling the state around?

Top row: the Fubini--Study geodesic sampled at equal arc length -- the reference
"clean" route from vacuum to |+Z_L>, generated by the brachistochrone Hamiltonian.
Bottom row: the state after each gate of an optimized displacement+SNAP sequence
reaching comparable fidelity.

Both rows start at vacuum and end at the target, so any difference in between is
the protocol's detour made visible -- the same quantity D_path scores numerically.
"""

import argparse
from pathlib import Path

import jax.numpy as jnp
import matplotlib.pyplot as plt
import numpy as np

from gkp_optimal_control.diagnostics import geodesic_curve, qsl_constants, trajectory_metrics
from gkp_optimal_control.gates import apply_generators, optimize_sequence, sequence_path_length
from gkp_optimal_control.plotting import plot_wigner, set_plot_style
from gkp_optimal_control.systems import build_gkp_system

REPO = Path(__file__).resolve().parent.parent


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--layers", type=int, default=3)
    ap.add_argument("--n-fock", type=int, default=100)
    ap.add_argument("--seeds", type=int, default=4)
    ap.add_argument("--maxiter", type=int, default=600)
    ap.add_argument("--bound", type=float, default=5.5)
    ap.add_argument("--out", default=str(REPO / "figures/gate_path_wigner.png"))
    args = ap.parse_args()

    set_plot_style()
    system, meta = build_gkp_system(n_fock=args.n_fock)
    qsl = qsl_constants(system, meta["n_phys"])

    fit = optimize_sequence(system, args.layers, meta["n_phys"], n_fock=args.n_fock,
                            seeds=args.seeds, maxiter=args.maxiter)
    _, traj, length = sequence_path_length(system.psi_init, fit["generators"], substeps=48)
    m = trajectory_metrics(traj, system, length=length, qsl=qsl)
    print(f"gate sequence: F={m['F']:.4f}  D_path={m['D_path']:.3f}  R_length={m['R_length']:.1f}")

    # State after each whole gate (substeps=1), prepended with the initial vacuum.
    _, per_gate = apply_generators(system.psi_init, fit["generators"], 1)
    gate_states = [system.psi_init] + [per_gate[i] for i in range(per_gate.shape[0])]
    n_col = len(gate_states)

    # Geodesic sampled at the same number of equal-arc-length waypoints.
    curve = geodesic_curve(system, 2001)
    idx = np.linspace(0, curve.shape[0] - 1, n_col).astype(int)
    geo_states = [curve[i] for i in idx]

    b = args.bound
    fig, axes = plt.subplots(2, n_col, figsize=(2.35 * n_col, 5.4))
    labels = ["vacuum"] + [("$D$" if k % 2 == 0 else "SNAP") + f"$_{{{k//2+1}}}$"
                           for k in range(n_col - 1)]

    for j, (g, q) in enumerate(zip(geo_states, gate_states)):
        plot_wigner(g, x_bound=b, y_bound=b, ax=axes[0, j], add_colorbar=False)
        plot_wigner(q, x_bound=b, y_bound=b, ax=axes[1, j], add_colorbar=False)
        axes[0, j].set_title(rf"$s={j/(n_col-1):.2f}\,\theta$", fontsize=11, pad=4)
        axes[1, j].set_title(labels[j], fontsize=11, pad=4)
        for r in (0, 1):
            axes[r, j].set_xlabel("")
            axes[r, j].set_ylabel("")
            axes[r, j].set_xticks([])
            axes[r, j].set_yticks([])

    axes[0, 0].set_ylabel("geodesic", fontsize=12)
    axes[1, 0].set_ylabel("gate sequence", fontsize=12)
    fig.suptitle(rf"Vacuum $\to |{{+}}Z_L\rangle$: the time-optimal path versus a "
                 rf"{args.layers}-layer gate sequence "
                 rf"($F={m['F']:.3f}$, $D_{{\mathrm{{path}}}}={m['D_path']:.2f}$)",
                 y=1.0, fontsize=13)
    fig.tight_layout()
    fig.savefig(args.out, dpi=140, bbox_inches="tight", facecolor="white")
    print(f"saved {args.out}")


if __name__ == "__main__":
    main()
