"""Figure: does a gate sequence follow a clean path, or fling the state around?

Top row: the Fubini--Study geodesic sampled at equal arc length -- the reference
"clean" route from vacuum to |+Z_L>, generated by the brachistochrone Hamiltonian.
Bottom row: the cavity state after each gate of an optimized sequence reaching
comparable fidelity, for either hardware instruction set.

Both rows start at vacuum and end at the target, so any difference in between is
the protocol's detour made visible -- the same quantity D_path scores numerically.

ECD is ancilla-mediated, so mid-sequence the cavity is *entangled* with the
transmon and its reduced state is mixed. Every panel therefore plots the Wigner
function of the reduced cavity density matrix Tr_qubit |psi><psi|, and the ECD row
is annotated with the cavity entanglement entropy S (nats; ln 2 = 0.693 is the
maximum for a qubit ancilla). The geodesic runs through product states with the
qubit in |g>, so S = 0 along it by construction -- the entropy is exactly the part
of the detour that a cavity-only Wigner picture cannot show.

Examples
--------
    uv run python scripts/plot_gate_path_wigner.py --family snap --layers 3
    uv run python scripts/plot_gate_path_wigner.py --family ecd --layers 16
"""

import argparse
from pathlib import Path

import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
import numpy as np
from jax import value_and_grad
from scipy.optimize import minimize

from gkp_optimal_control.diagnostics import geodesic_curve, qsl_constants, trajectory_metrics
from gkp_optimal_control.ecd import build_ecd_generators, build_ecd_system, cavity_entropy
from gkp_optimal_control.gates import apply_generators, optimize_sequence, sequence_path_length
from gkp_optimal_control.plotting import plot_wigner, set_plot_style
from gkp_optimal_control.systems import build_gkp_system

REPO = Path(__file__).resolve().parent.parent


def fit_ecd(system, n_fock, n_layers, *, seeds, maxiter, seed=0):
    """Multi-start L-BFGS over (Re b, Im b, theta, phi) per layer (fidelity only)."""

    def cost(flat):
        gens = build_ecd_generators(n_fock, flat.reshape(n_layers, 4))
        psi_f, _ = apply_generators(system.psi_init, gens, 1)
        return -jnp.abs(jnp.vdot(system.psi_targ, psi_f)) ** 2

    cg = jax.jit(value_and_grad(cost))

    def obj(x):
        v, g = cg(jnp.asarray(x))
        return float(v), np.asarray(g)

    rng = np.random.default_rng(seed)
    best_f, best_x = -1.0, None
    for _ in range(seeds):
        x0 = np.concatenate([
            rng.normal(0.0, 1.0, (n_layers, 2)),
            rng.uniform(0.0, np.pi, (n_layers, 1)),
            rng.uniform(0.0, 2 * np.pi, (n_layers, 1)),
        ], axis=1).ravel()
        res = minimize(obj, x0, jac=True, method="L-BFGS-B",
                       options={"maxiter": maxiter, "ftol": 1e-14, "gtol": 1e-12})
        if -res.fun > best_f:
            best_f, best_x = -res.fun, res.x
    return best_f, np.asarray(best_x)


def reduce_cavity(states, n_fock):
    """Partial trace over the qubit: joint kets -> cavity density matrices."""
    out = []
    for psi in states:
        mat = jnp.asarray(psi).reshape(n_fock, 2)          # (cavity, qubit)
        out.append(mat @ jnp.conj(mat).T)                  # Tr_qubit |psi><psi|
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--family", choices=["snap", "ecd"], default="snap")
    ap.add_argument("--layers", type=int, default=None,
                    help="default 3 for snap, 16 for ecd (fidelity-matched)")
    ap.add_argument("--n-fock", type=int, default=None,
                    help="default 100 for snap, 60 for ecd")
    ap.add_argument("--seeds", type=int, default=4)
    ap.add_argument("--maxiter", type=int, default=600)
    ap.add_argument("--bound", type=float, default=5.5)
    ap.add_argument("--max-cols", type=int, default=9,
                    help="cap on panels; longer sequences are subsampled evenly")
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    is_ecd = args.family == "ecd"
    n_layers = args.layers if args.layers is not None else (16 if is_ecd else 3)
    n_fock = args.n_fock if args.n_fock is not None else (60 if is_ecd else 100)
    # The SNAP figure keeps its original filename (referenced by the paper);
    # ECD gets a suffixed one.
    default_out = "figures/gate_path_wigner_ecd.png" if is_ecd else "figures/gate_path_wigner.png"
    out = args.out or str(REPO / default_out)

    set_plot_style()

    if is_ecd:
        system, meta = build_ecd_system(0.3, n_fock)
        qsl = qsl_constants(system, n_phys=meta["dim"])
        fidelity, x = fit_ecd(system, n_fock, n_layers,
                              seeds=args.seeds, maxiter=args.maxiter)
        gens = build_ecd_generators(n_fock, jnp.asarray(x).reshape(n_layers, 4))
        gate_labels = [lbl for k in range(n_layers)
                       for lbl in (rf"$R_{{{k+1}}}$", rf"ECD$_{{{k+1}}}$")]
        family_name = "ECD sequence"
    else:
        system, meta = build_gkp_system(n_fock=n_fock)
        qsl = qsl_constants(system, meta["n_phys"])
        fit = optimize_sequence(system, n_layers, meta["n_phys"], n_fock=n_fock,
                                seeds=args.seeds, maxiter=args.maxiter)
        gens = fit["generators"]
        gate_labels = [lbl for k in range(n_layers)
                       for lbl in (rf"$D_{{{k+1}}}$", rf"SNAP$_{{{k+1}}}$")]
        family_name = "gate sequence"

    _, traj, length = sequence_path_length(system.psi_init, gens, substeps=48)
    m = trajectory_metrics(traj, system, length=length, qsl=qsl)
    print(f"{args.family}: F={m['F']:.4f}  D_path={m['D_path']:.3f}  "
          f"R_length={m['R_length']:.1f}")

    # State after each whole gate, prepended with the initial vacuum.
    _, per_gate = apply_generators(system.psi_init, gens, 1)
    seq_states = [system.psi_init] + [per_gate[i] for i in range(per_gate.shape[0])]
    labels = ["vacuum"] + gate_labels

    # Subsample evenly if the sequence is longer than the panel budget.
    if len(seq_states) > args.max_cols:
        keep = np.linspace(0, len(seq_states) - 1, args.max_cols).astype(int)
        seq_states = [seq_states[i] for i in keep]
        labels = [labels[i] for i in keep]
    n_col = len(seq_states)

    # Geodesic at the same number of equal-arc-length waypoints.
    curve = geodesic_curve(system, 2001)
    idx = np.linspace(0, curve.shape[0] - 1, n_col).astype(int)
    geo_states = [curve[i] for i in idx]

    # For ECD everything lives on the joint space: trace out the qubit so the
    # panels are cavity Wigner functions in both rows.
    if is_ecd:
        entropy = cavity_entropy(jnp.stack(seq_states), n_fock)
        seq_plot = reduce_cavity(seq_states, n_fock)
        geo_plot = reduce_cavity(geo_states, n_fock)
    else:
        entropy = None
        seq_plot, geo_plot = seq_states, geo_states

    b = args.bound
    fig, axes = plt.subplots(2, n_col, figsize=(2.35 * n_col, 5.4))
    for j, (g, q) in enumerate(zip(geo_plot, seq_plot)):
        plot_wigner(g, x_bound=b, y_bound=b, ax=axes[0, j], add_colorbar=False)
        plot_wigner(q, x_bound=b, y_bound=b, ax=axes[1, j], add_colorbar=False)
        axes[0, j].set_title(rf"$s={j/(n_col-1):.2f}\,\theta$", fontsize=11, pad=4)
        sub = f"\n$S={entropy[j]:.2f}$" if entropy is not None else ""
        axes[1, j].set_title(labels[j] + sub, fontsize=11, pad=4)
        for r in (0, 1):
            axes[r, j].set_xlabel("")
            axes[r, j].set_ylabel("")
            axes[r, j].set_xticks([])
            axes[r, j].set_yticks([])

    axes[0, 0].set_ylabel("geodesic", fontsize=12)
    axes[1, 0].set_ylabel(family_name, fontsize=12)
    extra = (rf", $S_{{\max}}={entropy.max():.2f}$ nats" if entropy is not None else "")
    fig.suptitle(rf"Vacuum $\to |{{+}}Z_L\rangle$: the time-optimal path versus a "
                 rf"{n_layers}-layer {family_name} "
                 rf"($F={m['F']:.3f}$, $D_{{\mathrm{{path}}}}={m['D_path']:.2f}${extra})",
                 y=1.0, fontsize=13)
    fig.tight_layout()
    fig.savefig(out, dpi=140, bbox_inches="tight", facecolor="white")
    print(f"saved {out}")


if __name__ == "__main__":
    main()
